spring:
  application:
    name: config-client

server:
  port: 8087

#    spring.application.name=config-client
#    spring.cloud.config.label=master
#    spring.cloud.config.profile=dev
#    spring.cloud.config.uri= http://localhost:8888/
#    server.port=8881